# Generated by Django 4.0.2 on 2022-04-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название статьи')),
                ('description', models.CharField(max_length=500, verbose_name='Описание статьи')),
                ('full_text', models.TextField(max_length=5000, verbose_name='Содержание статьи')),
                ('image_for_main', models.ImageField(upload_to='media/image_for_main', verbose_name='Фото для статьи')),
                ('image_for_d', models.ImageField(upload_to='media/image_for_d', verbose_name='Фото для содержания статьи')),
                ('time', models.DateTimeField(unique=True, verbose_name='Время публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
