# Generated by Django 4.0.2 on 2022-03-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planets',
            options={'verbose_name': 'Планета', 'verbose_name_plural': 'Планеты'},
        ),
    ]
