# Generated by Django 4.0.2 on 2022-04-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название новости')),
                ('description', models.CharField(max_length=300, verbose_name='Описание новости')),
                ('full_text', models.TextField(max_length=5000, verbose_name='Содержание новости')),
                ('photo_for_main', models.ImageField(upload_to='media/photo_for_main', verbose_name='Фото для новости')),
                ('photo_for_d', models.ImageField(upload_to='media/photo_for_d', verbose_name='Фото для содержания новости')),
                ('time', models.DateTimeField(unique=True, verbose_name='Время публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
